service: node-mongo-test
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: sa-east-1

plugins:
  - serverless-plugin-datadog

custom:
  datadog:
    addExtension: true
    apiKey: ${env:DD_API_KEY}

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /users/create
          method: get
